### ISSUE TITLE
Не работает в версии IntelliJ IDEA 2019.3.2

### ISSUE THREAD

**Issue by toptun80** [andrey4623/intellij-rainbow-csv#4]
### **Описание**
После обновления IDEA до версии 2019.3.2 не работает ни с включенным CSVplugin, ни с выключенным.
#### Non-Bundled Plugins: Lombook Plugin, com.andrey4623.rainbowcsv, com.rybkin.jbehave.example-table-formatter, jbehave-support-plugin, jbehave-support-plugin-extension, org.bigtesting.jbehave.buddy, training 

<img width="1092" alt="Снимок экрана 2020-01-22 в 18 35 27" src="https://user-images.githubusercontent.com/54706630/72908177-30907500-3d46-11ea-992b-8c6332fd38d3.png">

**Comment by SeeSharpSoft** [comment]
FYI: https://github.com/SeeSharpSoft/intellij-csv-validator#column-highlighting-colors

**Comment by toptun80** [comment]
> FYI: https://github.com/SeeSharpSoft/intellij-csv-validator#column-highlighting-colors

<img width="831" alt="Снимок экрана 2020-01-23 в 22 13 52" src="https://user-images.githubusercontent.com/54706630/73016265-98ba8600-3e2e-11ea-9fab-1694a1ce5d6f.png">

**Comment by SeeSharpSoft** [comment]
#column-highlighting-colors => https://github.com/SeeSharpSoft/intellij-csv-validator#color-scheme

**Comment by toptun80** [comment]
> FYI: https://github.com/SeeSharpSoft/intellij-csv-validator#column-highlighting-colors

### И так не работает

<img width="831" alt="Снимок экрана 2020-01-23 в 22 49 22" src="https://user-images.githubusercontent.com/54706630/73018518-d7ead600-3e32-11ea-9c82-e333b9f2f480.png">

**Comment by SeeSharpSoft** [comment]
![image](https://user-images.githubusercontent.com/3205800/73019324-a6b6d980-3e23-11ea-9652-ce61debfb978.png)

**Comment by toptun80** [comment]
<img width="627" alt="Снимок экрана 2020-01-23 в 23 20 21" src="https://user-images.githubusercontent.com/54706630/73020833-7d07ad80-3e37-11ea-8e1d-b9e331a1d804.png">

**Comment by SeeSharpSoft** [comment]
![image](https://user-images.githubusercontent.com/3205800/73021517-0adb9c80-3e28-11ea-93a2-91a4de5a2ec8.png)

деактивировать другие плагины CSV ([Google translate](https://translate.google.com/?rlz=1C1CHBF_deDE782DE782&um=1&ie=UTF-8&hl=en&client=tw-ob#en/ru/deactivate%20other%20CSV%20plugins) 😄)

**Comment by toptun80** [comment]
> деактивировать другие плагины CSV

Good translate :)
Все другие плагины деактивированы. Я проверял все возможные варианты и сочетания. Включал и выключал. Плагин Rainbow CSV не работает ни в каком варианте.
Это произошло сразу же после обновления IDEA на моем MacBook.
До обновления IDEA это все работало без танцев с бубном у костра :)

**Comment by SeeSharpSoft** [comment]
IDEA Version & Plugin Version?

надеюсь, никто не возражает против нас, угоняющих этот репо...

**Comment by SeeSharpSoft** [comment]
только что вспомнил твой первый комментарий... IC-193 & CSV 2.8.2, работает для меня 😕

**Comment by andrey4623** [comment]
@toptun80 Спасибо за сообщение об ошибке! Можете, пожалуйста, проверить, работает ли у вас версия 1.5?

**Comment by toptun80** [comment]
@andrey4623 да, все ок, работает! Спасибо!
